---
version: 2.1


executors:
  default_node:
    docker:
      - image: circleci/node:10

node_key: &node_key
  key: node-deps-{{ checksum "yarn.lock" }}

commands:
  restore_node_cache:
    description: "restore node modules from cache"
    steps:
      - restore_cache:
          <<: *node_key

  save_node_cache:
    description: "save node modules to cache"
    steps:
      - save_cache:
          <<: *node_key
          paths:
            - node_modules

  install_node_dependencies:
    description: "Install node dependencies"
    steps:
      - run:
          command: |
            if [ ! -d node_modules ]; then
              yarn --pure-lockfile
            fi

  deploy_to_gstorage:
    description: "Deploy app to a Google Storage bucket"
    parameters:
      bucket:
        type: string
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "[gsutil] deploy to Google Storage"
          command: |
            gsutil rsync -R build << parameters.bucket >>

  build_app:
    description: "Build app"
    parameters:
      env:
        description: "The environment prefix to remove on all env vars"
        type: string
    steps:
      - run:
          name: "build app"
          command: |
            env | sed -n "s/^<< parameters.env >>_//p" >> .env
            yarn build


jobs:
  build:
    description: "build app"
    parameters:
      env:
        description: "The environment prefix to remove on all env vars"
        type: string
    executor: default_node
    steps:
      - checkout
      - restore_node_cache
      - install_node_dependencies
      - build_app:
          env: << parameters.env >>
      - persist_to_workspace:
          root: .
          paths:
            - build
      - save_node_cache

  deploy:
    description: "deploy app"
    executor: default_node
    parameters:
      bucket:
        description: "URL of the Google storage bucket the app is deployed to"
        type: string
    steps:
      - run:
          name: "[install] install GCloud SDK"
          command: |
            curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --disable-prompts
            ~/google-cloud-sdk/install.sh --usage-reporting=false --path-update=true --bash-completion=true --rc-path=~/.bashrc
            sudo ln -s ~/google-cloud-sdk/bin/gcloud /usr/bin
            sudo ln -s ~/google-cloud-sdk/bin/gsutil /usr/bin
      - run:
          name: "[gcloud] authenticate GCloud SDK"
          command: |
            echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > $HOME/gcloud-service-key.json
            gcloud auth activate-service-account --key-file $HOME/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT
      - deploy_to_gstorage:
          bucket: <<parameters.bucket>>


workflows:

  just-build-other-branches:
    jobs:
      - build:
          env: DEMO
          filters:
            branches:
              ignore: master

  build-deploy-staging:
    jobs:
      - build:
          env: DEMO
          filters:
            branches:
              only: master
      - deploy:
          bucket: gs://staging-transformer.en-marche.fr
          requires:
            - build

  build-deploy-prod:
    jobs:
      - build:
          env: PROD
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          bucket: gs://transformer.en-marche.fr
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - build
