---
version: 2.1
templates:
  defaults: &defaults
    docker:
      - image: google/cloud-sdk

  node_key: &node_key
    key: node-deps-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}

  restore_node: &restore_node
    restore_cache:
      <<: *node_key

  deploy_static: &deploy_static
    <<: *defaults
    parameters:
      bucket:
        description: "URL of the Google storage bucket the app is deployed to"
        type: string
    steps:
      - checkout
      - <<: *restore_node
      - run:
          name: Build application
          command: |
            env | sed -n "s/^${ENV}_//p" >> .env
            yarn build
      - run:
          name: Install GCloud SDK
          command: |
            curl -sSL https://sdk.cloud.google.com > /tmp/gcl && bash /tmp/gcl --disable-prompts
            ~/google-cloud-sdk/install.sh --usage-reporting=false --path-update=true --bash-completion=true --rc-path=~/.bashrc
            sudo ln -s ~/google-cloud-sdk/bin/gcloud /usr/bin
            sudo ln -s ~/google-cloud-sdk/bin/gsutil /usr/bin
      - run:
          name: Authenticate GCloud SDK
          command: |
            echo "${GCLOUD_SERVICE_KEY}" | base64 --decode > $HOME/gcloud-service-key.json
            gcloud auth activate-service-account --key-file $HOME/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT
      - deploy:
          name: Deploy to Google Storage
          command: |
            gsutil rsync -R build << parameters.bucket >>

  deploy_dev: &deploy_dev
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node
      - add_ssh_keys:
          fingerprints:
            - "c7:b5:c4:c5:4a:4b:5d:4e:42:b6:f9:53:fa:38:36:23"
      - deploy:
          name: Deploy to GitHub Pages
          command: |
            sed -i 's/"homepage": ""/"homepage": "https:\/\/enmarche.github.io\/transformer.en-marche.fr"/' package.json
            git config --global user.email "deploy@circleci"
            git config --global user.name "deploy bot"
            env | sed -n "s/^DEV_//p" >> .env
            yarn deploy


  filter_demo: &filter_demo
    filters:
      branches:
        only: master
      tags:
        only: demo

  filter_prod: &filter_prod
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v[0-9]+\.[0-9]+\.[0-9]+/

jobs:
  build-static:
    <<: *defaults
    steps:
      - checkout

      - <<: *restore_node
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          <<: *node_key
          paths:
            - node_modules

  deploy-static-demo:
    environment:
      ENV: DEMO
    <<: *deploy_static

  deploy-static-prod:
    environment:
      ENV: PROD
    <<: *deploy_static

  deploy-static-dev:
    <<: *deploy_dev

workflows:
  version: 2
  deploy-demo:
    jobs:
      - build-static:
          <<: *filter_demo
      - deploy-static-demo:
          <<: *filter_demo
          bucket: gs://staging-transformer.en-marche.fr
          requires:
            - build-static

  deploy-prod:
    jobs:
      - build-static:
          <<: *filter_prod
      - deploy-static-prod:
          <<: *filter_prod
          bucket: gs://transformer.en-marche.fr
          requires:
            - build-static
